---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-access-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka-access-controller.io
  resources:
  - kafkaaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka-access-controller.io
  resources:
  - kafkaaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - kafka-access-controller.io
  resources:
  - kafkaaccesses/status
  verbs:
  - get
  - patch
  - update
