#!/usr/bin/env bash
# Copy the controller-gen CRD and RBAC from config/ into the Helm chart,
# wrapped in the templating the chart needs.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
chart="$root/charts/kafka-access-controller/templates"
crd_src="$root/config/crd/kafka-access-controller.io_kafkaaccesses.yaml"
rbac_src="$root/config/rbac/role.yaml"

banner='{{/*
  GENERATED by hack/sync-chart.sh from %s -- do not edit.
  Change the kubebuilder markers in the Go source and run `make generate`.
*/}}'

# --- CRD -------------------------------------------------------------------
{
  printf "$banner\n" "config/crd/"
  echo '{{- if .Values.crds.install }}'
  # Strip the leading document separator controller-gen emits; the conditional
  # above has to be the first thing in the rendered document.
  sed '1{/^---$/d;}' "$crd_src" |
    # Escape {{ in CRD descriptions, which Helm would evaluate.
    sed 's/{{/{{"{{"}}/g' |
    # The keep annotation has to go inside metadata.annotations, so it is
    # injected rather than appended.
    awk '
      /^  annotations:$/ && !done {
        print
        print "    {{- if .Values.crds.keep }}"
        print "    helm.sh/resource-policy: keep"
        print "    {{- end }}"
        done = 1
        next
      }
      { print }
    '
  echo '{{- end }}'
} > "$chart/crds.yaml"

# --- RBAC ------------------------------------------------------------------
{
  printf "$banner\n" "config/rbac/role.yaml"
  echo '{{- if .Values.rbac.create }}'
  echo 'apiVersion: rbac.authorization.k8s.io/v1'
  echo 'kind: ClusterRole'
  echo 'metadata:'
  echo '  name: {{ include "kafka-access-controller.fullname" . }}'
  echo '  labels:'
  echo '    {{- include "kafka-access-controller.labels" . | nindent 4 }}'
  # Everything from `rules:` down is generated verbatim.
  sed -n '/^rules:/,$p' "$rbac_src"
  cat <<'YAML'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafka-access-controller.fullname" . }}
  labels:
    {{- include "kafka-access-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kafka-access-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-access-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.enableLeaderElection }}
---
{{/*
  Leader election is namespaced and deliberately not part of the generated
  ClusterRole: the markers on the reconciler describe what it does to
  KafkaAccess resources, not how the manager elects itself.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kafka-access-controller.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-access-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-access-controller.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-access-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka-access-controller.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-access-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
YAML
  echo '{{- end }}'
} > "$chart/rbac.yaml"

echo "synced chart templates from config/"
