{{- if .Values.podDisruptionBudget }}
{{/*
A PDB only helps with more than one replica; with one, minAvailable: 1 blocks
node drains.
*/}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kafka-controller.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
